stages:
  - test


before_script:
  - pod install
  - xcodebuild clean -workspace iParapheur.xcworkspace -scheme iParapheur -quiet
  - rm -rf /tmp/GitLabRunner_derivedData


xctest:
  stage: test
  retry: 2
  coverage: '/^\d+\s+iParapheur\.app\s+\d\d\s+(\d+\.\d+)\%/'
  script:
    - xcodebuild test -workspace iParapheur.xcworkspace -scheme iParapheur -destination 'platform=iOS Simulator,name=iPad Air 2,OS=11.1' -derivedDataPath /tmp/GitLabRunner_derivedData/ -enableCodeCoverage YES -quiet
    - xcrun xccov view /tmp/GitLabRunner_derivedData/Logs/Test/*.xcresult/1_Test/action.xccovreport --only-targets


sonarqube:
  stage: test
  only:
    - develop
  script:
    # Dependancies to install on the runner : https://github.com/Backelite/sonar-swift
    - ./run-sonar-swift.sh