
stages:
  - build

build_project:
  stage: build
  script:
    - pod install
    - xcodebuild clean -workspace iParapheur.xcworkspace -scheme iParapheur -quiet
    - rm -rf /tmp/GitLabRunner_derivedData
    - xcodebuild test -workspace iParapheur.xcworkspace -scheme iParapheur -destination 'platform=iOS Simulator,name=iPad Air 2,OS=11.1' -derivedDataPath /tmp/GitLabRunner_derivedData/ -enableCodeCoverage YES -quiet
    # Regex to retrieve the code coverage (should be set in Project Settings) : ^\d+\s+iParapheur\.app\s+\d\d\s+(\d+\.\d+)\%
    - xcrun xccov view /tmp/GitLabRunner_derivedData/Logs/Test/*.xcresult/1_Test/action.xccovreport --only-targets

