stages:
  - build

build_project:
  stage: build
  script:
    - su runner -c "pod install"
    - ls -l
    - xcodebuild clean -workspace iParapheur.xcworkspace -scheme iParapheur | xcpretty
    - xcodebuild test -workspace iParapheur.xcworkspace -scheme iParapheur -destination 'platform=iOS Simulator,name=iPad Air 2,OS=11.1' | xcpretty
    - slather coverage -s --workspace iParapheur.xcworkspace --scheme iParapheur iParapheur.xcodeproj